name = "thirdparty-custom-posture"
workers_dev = false
compatibility_date = "2024-08-22"
main = "index.js"

# replace with your custom domain
routes = [
  { pattern = "customposture.red1flare.com", custom_domain = true }
]

[observability]
enabled = true

# replace the variables with the your access policy, team domain and the serial number of the devices that should pass the posture check
[vars]
POLICY_AUD="5d0cbc268ebad4371b225d048eac8761234bbbe6da38ab94dd7f43c9c8d2b481"
TEAM_DOMAIN="red1team.cloudflareaccess.com"
POSTURE_PASS = { WIN10_VM_SERIAL = "8479-5166-5206-4065-3284-5980-02" , LENOVO_LAPTOP_SERIAL = "YD04512N" }
